server:
  port: "${LICENSE_SERVER_PORT:18806}"

spring:
  http:
    encoding:
      charset: utf-8

  # 国际化
  messages:
    # 国际化文件的保存目录和基名
    basename: i18n/messages
    # 加载的资源文件缓存失效时间,默认为永远
    cache-duration: 3600s
    # 找不到对应的locale是是否使用系统locale
    fallback-to-system-locale: true


# mybatis分页插件
pagehelper:
  # 数据库方言
  helper-dialect: mysql
  # 当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
  page-size-zero: false
  # 默认值为 false ，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页
  offset-as-page-num: false
  # 默认值为false，该参数对使用RowBounds作为分页参数时有效。当该参数设置为 true 时，使用 RowBounds 分页会进行 count 查询。
  row-bounds-with-count: true
  # 分页合理化参数，默认值为 false。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页。默认 false 时，直接根据参数进行查询。
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数，默认值 false ，分页插件会从查询方法的参数值中，自动根据params配置的字段中取值，查找到合适的
  #值时就会自动分页
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，可以配置pageNum,pageSize,count,pageSizeZero,reasonable ，
  #不配置映射的用默认值， 默认值为 pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero= pageSizeZero
  params: count:countSql

# mybatis配置
mybatis:
  type-aliases-package: com.topband.bluetooth.mapper
  # mybatis xml配置文件所在路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 指定 MyBatis 所用日志的具体实现，未指定时将自动查找
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 指定 MyBatis 增加到日志名称的前缀
    log-prefix: executableSql.


# logback配置文件目录
logging:
  config: classpath:logs/logback.xml
  level:
    com.alibaba.nacos.client.naming: WARN
    executableSql: debug

example:
  property: "I AM IN THE DEFAULT"


